### ISSUE TITLE
Fase de Carga de Documentos: Debe ingresar documentos del listado del 1 al 15.​

### ISSUE THREAD

**Issue by angelscmx** [JavierBerdeja/APIBCS-Proveedores#5]
Fase de Carga de Documentos: Debe ingresar documentos del listado del 1 al 15.​

![Image](https://github.com/JavierBerdeja/APIBCS-Proveedores/assets/155853199/ca8e92f7-0a46-4072-84de-318383d7d88d)

<html>
<body>

01​ | Acta(s) Constitutiva(s)​
-- | --
02​ | Poder Notarial Representante Legal​
03​ | Comprobante de Domicilio​
04​ | Constancia de Situación Fiscal​
05​ | Opinión de Cumplimiento POSITIVA​
06​ | Opinión del Cumplimiento IMSS​
07​ | Opinión del Cumplimiento INFONAVIT​
08​ | Alta Patronal IMSS​
09​ | Carátula Estado de Cuenta Bancario (CLABE)​
10​ | Declaración Anual del ejercicio inmediato anterior​
11​ | Pago Declaración Anual del ejercicio inmediato anterior​
12​ | Acuse Recibo de declaración mensual IVA mas reciente​
13​ | Acuse Recibo de declaración mensual RFC mas reciente​
14​ | Pago de acuse recibo de declaración mensual IVA mas reciente​
15​ | Pago de acuse recibo de declaración mensual ISR mas reciente​

</body>
</html>

**Comment by angelscmx** [comment]
- para cada documento hay que definir nombre de archivo de carga.
- en configuracion hay que definir tamaño maximo y tipo de carga
- para el 1 doc --- acta consttituva ---  debe de permitir mas de un doc
-

**Comment by JavierBerdeja** [comment]
- No es necesario que los archivos tengan un nombre específico antes de subirlos, debido a que el portal puede guardarlos con el nombre que se requiera.

**Comment by angelscmx** [comment]
![Image](https://github.com/JavierBerdeja/APIBCS-Proveedores/assets/155853199/67c6d5df-b212-4775-b520-87ed33ccbb6b)

no tiene permisos para subir documentos

**Comment by angelscmx** [comment]
aplicar permisos para poder subir los documentos

**Comment by angelscmx** [comment]
todo correcto
